### ISSUE TITLE
Civix hook documentation points to the wiki

### ISSUE THREAD

**Issue by jaapjansma** [totten/civix#123]
The civix generate:module command generates a basic template file with basic hooks in it. Each hook has a comment pointing to the docs.

However the url used is the one of the wiki. This should be docs.civicrm.org

Example as it is now:
```php
/**
 * Implements hook_civicrm_config().
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_config
 */
function action_provider_civicrm_config(&$config) {
  _action_provider_civix_civicrm_config($config);
}
```

**Comment by seamuslee001** [comment]
I think this has been resolved in recent civix versions @totten
