### ISSUE TITLE
Error with generate:entity-boilerplate

### ISSUE THREAD

**Issue by kaianuar** [totten/civix#135]
After following the tutorial with no other errors I get to Generate your DAO and SQL files step

After running this command civix generate:entity-boilerplate -vvv this is the output

[Bootstrap] Options: {
    "dynamicSettingsFile": "phar:///home/vagrant/buildkit/bin/civix/vendor/civicrm/cv/settings_location.php",
    "env": "CIVICRM_SETTINGS",
    "prefetch": false,
    "settingsFile": null,
    "search": true,
    "cmsType": null,
    "httpHost": "",
    "output": {

    }
}
[Bootstrap] Find settings file
[Bootstrap] Load supplemental configuration for "/srv/www/d7-46/sites/default/civicrm.settings.php"
[Bootstrap] Load settings file "/srv/www/d7-46/sites/default/civicrm.settings.php"
[Bootstrap] Find CMS root for "/srv/www/d7-46/sites/default/ext/com.kai.membership"
[Bootstrap] Found "drupal" in "/srv/www/d7-46"
[Bootstrap] Simulate web environment in CLI
[Bootstrap] Initialize class loader
[Bootstrap] Finished
PHP Fatal error:  Call to undefined method CRM_Utils_System::majorVersion() in phar:///home/vagrant/buildkit/bin/civix/src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php on line 60
PHP Stack trace:
PHP   1. {main}() /home/vagrant/buildkit/bin/civix:0
PHP   2. require() /home/vagrant/buildkit/bin/civix:10
PHP   3. CRM\CivixBundle\Application::main() phar:///home/vagrant/buildkit/bin/civix/bin/civix:22
PHP   4. Symfony\Component\Console\Application->run() phar:///home/vagrant/buildkit/bin/civix/src/CRM/CivixBundle/Application.php:35
PHP   5. Symfony\Component\Console\Application->doRun() phar:///home/vagrant/buildkit/bin/civix/vendor/symfony/console/Application.php:124
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///home/vagrant/buildkit/bin/civix/vendor/symfony/console/Application.php:193
PHP   7. Symfony\Component\Console\Command\Command->run() phar:///home/vagrant/buildkit/bin/civix/vendor/symfony/console/Application.php:850
PHP   8. CRM\CivixBundle\Command\AddEntityBoilerplateCommand->execute() phar:///home/vagrant/buildkit/bin/civix/vendor/symfony/console/Command/Command.php:257

Any ideas?

**Comment by chamilwijesooriya** [comment]
[as mentioned here](https://github.com/totten/civix/issues/136) please upgrade to CiviCRM 4.7

**Comment by totten** [comment]
Thanks for diagnosing and cross-linking @chamilwijesooriya.

@michaelmcandrew @kaianuar  @tanseercena, I'm inclined to simply return a nicer error if you run this subcommand on 4.6 (5c1d09e).

**Comment by michaelmcandrew** [comment]
@totten - agreed.
