### ISSUE TITLE
Fatal Error when run civix generate:entity-boilerplate

### ISSUE THREAD

**Issue by tanseercena** [totten/civix#136]
I get fatal error when I run: civix generate:entity-boilerplate
Error: 
PHP Fatal error:  Call to undefined method CRM_Utils_System::majorVersion() in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Command/AddEntityBoilerplateCommand.php on line 60

**Comment by tanseercena** [comment]
This issue solved when upgrade to 4.7. Thanks

**Comment by totten** [comment]
Thanks for diagnosing and cross-linking @chamilwijesooriya. Closing as it duplicates #135 and upgrading worked for @tanseercena.
