### ISSUE TITLE
_hook_civix_civicrm_alterSettingsFolders only effective on first invocation

### ISSUE THREAD

**Issue by michaelmcandrew** [totten/civix#139]
_hook_civix_civicrm_alterSettingsFolders checks to see if it has already been called and if so, it returns early without adding directories to $metaDataFolders

This logic breaks down for any pathways where it gets called twice (I've come across two of these - there might be others).

A simple solution is to remove the 'is configured' check.

```php
  static $configured = FALSE;
  if ($configured) {
    return;
  }
  $configured = TRUE;
```

A less simple solution (if we are worried about the extra call to is_dir() call would be

```php
  static $configured = FALSE;
  static $settingsDir = NULL;

  if (!$configured) {
    $settingsDir = __DIR__ . DIRECTORY_SEPARATOR . 'settings';
    if (!is_dir($settingsDir)) {
      $settingsDir = NULL;
    }
    $configured = TRUE;
  }
  if ($settingsDir && !in_array($settingsDir, $metaDataFolders)) {
    $metaDataFolders[] = $settingsDir;
  }
```
Both the above solutions leave extensions that currently depend on this functionality liable to break.

An alternative approach would be to patch core so that CRM_Utils_Hook::alterSettingsFolders($metaDataFolders); is only ever called once and we cache the result, but not sure how feasible that is.

**Comment by michaelmcandrew** [comment]
I'm thinking that we might want to include an upgrade message with the next version of civix to address this (suggest people edit their extension.civix.php files)

**Comment by totten** [comment]
@michaelmcandrew good analysis.

(For anyone reading newly, the full text of the template being discussed is...)

https://github.com/totten/civix/blob/008e9aa61c0040f2edb5392c0bd1d51a15a9de8c/src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php#L439-L450

TBH, I don't really know why it has a `static $configured` guard. Tracing the records, it wasn't part of a bugfix in civix -- it was apparently copied-pasted from the original exemplar in #29. @eileenmcnaughton might have a better idea.

My suspicion -- it borrowed from `_hook_civix_civicrm_config` which uses a `static $configured` guard as a very fast way to prevent duplicate changes in global state. However, IMHO, there are few differences between these:

1. `h_c_alterSettingsFolder` has another guard (`is_dir(...) && !in_array(...)`) which looks more substantive and correct.
2. The final value of `$metaDataFolders` is cached. This means we don't have to fire the hook on every page-request. So it's OK if each hook listener spends an extra 2ms on more expensive guards.
3. The consequences of `h_c_alterSettingsFolder` are fully represented by the parameter (`&$metaDataFolders`). By contrast, `h_c_config` manipulates global state (`include_path`, etc). When faced with various flushes/resets, it's easier to reason about multiple iterations of `h_c_alterSettingsFolder` than `h_c_config`.

Overall, I'm 👍 to remove the `static $configured` guard from `h_c_alterSettingsFolder` (unless Eileen has a reason not to).

**Comment by eileenmcnaughton** [comment]
I'm OK with removing it

**Comment by totten** [comment]
Thanks, @eileenmcnaughton. So, @michaelmcandrew, guess we're good to continue. Were you thinking to do a PR?

Regarding this:

> I'm thinking that we might want to include an upgrade message with the next version of civix to address this (suggest people edit their extension.civix.php files)

Depends how you mean...

* (*Easy way*) Send a public service announcement (PSA) to `civicrm-dev@`
* (*Easy way*) Add another line to https://github.com/totten/civix/blob/master/UPGRADE.md (It's not strictly needed since the doc advises an update generally, but there's no harm in giving #139 a call-out with the others.)
* (*Hard way*) Display a message in the CLI if the `*.civix.php` is old
    * This would be cool, especially if it was a generalized warning about stale templates. We'd probably need some kind of tracking-code (embedded in each generated file and/or `info.xml`). But it's probably a few hours work.

I think the easy way is fine. :)

**Comment by michaelmcandrew** [comment]
@totten see above for PR. If you are into batching PR reviews, you might want to check out #134 and #138 at the same time :)
