### ISSUE TITLE
generate:angular-page should use LONG_NAME in CRM.ts() call

### ISSUE THREAD

**Issue by scardinius** [totten/civix#149]
Hi,

angular module contains such code:

```js
var ts = $scope.ts = CRM.ts('canarius'); // generated module
var ts = $scope.ts = CRM.ts('<?php echo $tsDomain ?>'); // civix view
```

but it does not work for me, CiviCRM 5.10.4. When I changed it to E::LONG_NAME then it's fine
```js
var ts = $scope.ts = CRM.ts('eu.caltha.canarius');
```

**Comment by samuelsov** [comment]
The doc indicate that we need the LONG_NAME for this - https://docs.civicrm.org/dev/en/latest/translation/extensions/

Also, the working example i have with angular + ts confirm this.

**Comment by totten** [comment]
Thanks @scardinius for the report and @samuelsov for the verification!

**Comment by totten** [comment]
Patch merged.

Thanks again. Also, cheers at @seamuslee001 for doing a round of triage and calling this issue out on MM.
