### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by adixon** [totten/civix#206]
Extensions using civix are generating the above deprecation notice (as of civicrm 5.34.0, at least).

The offending code is just some old backward compatibility stuff to support CiviCRM versions less than 4.3.

https://github.com/totten/civix/blob/f695795a51ce9d9e36f6b6029a3779856642a8ec/src/CRM/CivixBundle/Resources/views/Code/module.civix.php.php#L234

PR forthcoming.

**Comment by eileenmcnaughton** [comment]
@adixon I don't have rights to close this but looks like a fix was merged

**Comment by adixon** [comment]
Yup!
