### ISSUE TITLE
"cv en" in README.md is not valid for WordPress installs?

### ISSUE THREAD

**Issue by ChrisHardie** [totten/civix#216]
In creating my first CiviCRM extension with civix, I noticed that the generated README contains instructions to use `cv en` to enable a newly cloned extension. This subcommand does not appear to be valid for WordPress-based installations.

https://github.com/totten/civix/blob/master/src/CRM/CivixBundle/Resources/views/Code/readme.md.php#L36

Maybe there's a way to make the generated README instructions more universally useful?

**Comment by MegaphoneJon** [comment]
Hi Chris,

`cv en` works for me on WordPress.  Could you please provide the output of the `cv` command?

**Comment by ChrisHardie** [comment]
Oh, interesting! Here's what I'm seeing:

```
$ wp cv en com.chrishardie.slacknotifications
Error: Unrecognized command - 'en'
```

Other `cv` subcommands work fine. Here's the list of commands that `wp help cv` says are available:

>   wp civicrm api
>   ===============
>   Command for accessing CiviCRM APIs. Syntax is identical to drush cvap.
> 
>   wp civicrm cache-clear
>   ===============
>   Command for accessing clearing cache.  Equivilant of running civicrm/admin/setting/updateConfigBackend&reset=1
> 
>   wp civicrm enable-debug
>   ===============
>   Command for to turn debug on.
> 
>   wp civicrm disable-debug
>   ===============
>   Command for to turn debug off.
> 
>   wp civicrm member-records
>   ===============
>   Run the CiviMember UpdateMembershipRecord cron (civicrm member-records).
> 
>   wp civicrm process-mail-queue
>   ===============
>   Process pending CiviMail mailing jobs.
>   Example:
>   wp civicrm process-mail-queue -u admin
> 
>   wp civicrm rest
>   ===============
>   Rest interface for accessing CiviCRM APIs. It can return xml or json formatted data.
> 
>   wp civicrm restore
>   ==================
>   Restore CiviCRM codebase and database back from the specified backup directory
> 
>   wp civicrm sql-conf
>   ===================
>   Show civicrm database connection details.
> 
>   wp civicrm sql-connect
>   ======================
>   A string which connects to the civicrm database.
> 
>   wp civicrm sql-cli
>   ==================
>   Quickly enter the mysql command line.
> 
>   wp civicrm sql-dump
>   ===================
>   Prints the whole CiviCRM database to STDOUT or save to a file.
> 
>   wp civicrm sql-query
>   ====================
>   Usage: wp civicrm sql-query <query> <options>...
>   <query> is a SQL statement, which can alternatively be passed via STDIN. Any additional arguments are passed to the mysql command directly.";
> 
>   wp civicrm update-cfg
>   =====================
>   Update config_backend to correct config settings, especially when the CiviCRM site has been cloned / migrated.
> 
>   wp civicrm upgrade
>   ==================
>   Take backups, replace CiviCRM codebase with new specified tarfile and upgrade database by executing the CiviCRM upgrade process - civicrm/upgrade?reset=1. Use civicrm-restore to revert
>   to previous state in case anything goes wrong.
> 
>   wp civicrm upgrade-db
>   =====================
>   Run civicrm/upgrade?reset=1 just as a web browser would.
> 
>   wp civicrm install
>   ===============
>   Command for to install CiviCRM.  The install command requires that you have downloaded a tarball or zip file first.

**Comment by MegaphoneJon** [comment]
Ah - there's the confusion.  `cv` is a [separate CLI utility](https://github.com/civicrm/cv) from `wp-cli`.  It's unfortunate that `cv` is also the alias for the `civicrm` subcommand in wp-cli.

If you'll be working with CiviCRM on the CLI for any appreciable amount, I strongly recommend installing it - but if not, you can get similar results with `wp cv api Extension.install keys="xyz"`.

May I ask what your extension is?  I keep on top of the extension ecosystem and may be able to point you to something similar if it exists.

**Comment by ChrisHardie** [comment]
Thank you. I'm pretty much brand new to CiviCRM so I hadn't come across that distinction yet. Oops!

Here's the simple extension I built: https://github.com/ChrisHardie/civicrm-slack-notifications
Blog post: https://tech.chrishardie.com/2021/civicrm-extension-slack-notifications/

I did a fair amount of searching for something similar and couldn't find it, so I will be embarrassed in a good way if I missed some other great source of extensions. :) Thanks again.

**Comment by MegaphoneJon** [comment]
Very cool!  I've actually thought a lot about building a generic "send webhook" action to [CiviRules](https://lab.civicrm.org/extensions/civirules/).

You seem to have done a pretty good job, and I imagine your itch is scratched - but if you end up wanting finer-grained controls, you may want to port this code to a CiviRules action.  That way, CiviRules can handle all the conditions ("only send if donation is over $100", etc.) and your extension can just handle the notification portion.

**Comment by ChrisHardie** [comment]
Great idea! Next time I touch it for any significant updates, I may shift to that approach. I've not done much with CiviRules yet; I can see how this would be more powerful and flexible in the long run.
