### ISSUE TITLE
civix generate:entity-boilerplate does not add Engine=InnoDb to the auto_install.sql

### ISSUE THREAD

**Issue by jaapjansma** [totten/civix#217]
The command `civix generate:entity-boilerplate` does not add the `ENGINE=InnoDb` satement to the auto_install.sql.

**Comment by mattwire** [comment]
Agree that it should do - we have to add it manually at the moment and it's proven to be necessary because there are quite a few servers that don't default to InnoDb

**Comment by jaapjansma** [comment]
Any idea how this can be fixed?

**Comment by mattwire** [comment]
It looks like this relies on the core `CRM_Core_CodeGen_Schema::generateCreateSql()` code and maybe needs to be fixed there.

**Comment by jaapjansma** [comment]
I have added a PR: https://github.com/totten/civix/pull/220

**Comment by totten** [comment]
Released in v21.04.1.

**Comment by mattwire** [comment]
Thanks @jaapjansma @totten :-)
