### ISSUE TITLE
`civix generate:upgrader` should use core upgrader (5.38+)

### ISSUE THREAD

**Issue by totten** [totten/civix#221]
This a follow-up to https://lab.civicrm.org/dev/core/-/issues/2547 and https://github.com/civicrm/civicrm-core/pull/20090. Beginning with civicrm-core in v5.38+, the `CRM_*_Upgrader_Base` will be available as `CRM_Extension_Upgrader_Base`. This means that:

* We won't need so much boilerplate.
* Upgrade steps are sorted on extension dependencies (more primitive ext's are upgraded before more dependent ext's)
* It will be easier to do patches/fixes on the base upgrader (e.g. if we need to distinguish the upgrade steps defined by each ext).

However, extensions will need a transition. For a manual transition, the steps are:

1. Edit `CRM/Myext/Upgrader.php`. Change the base-class from `CRM_Myext_Upgrader_Base` to `CRM_Extension_Upgrader_Base`.
2. Edit `info.xml`.
    * Ensure that `<classloader>` has a `<psr0>` statement
    * Ensure that `<upgrader>` points to `CRM_Myext_Upgrader`
3. Delete `CRM/Myext/Upgrader/Base.php`
4. Remove old stubs from `myext.php` (ie `myext_civicrm_{install,disable,enable,uninstall,upgrade}`)
5. Optionally, remove old stubs from `myext.civix.php` (ie `myext_civicrm_{install,disable,enable,uninstall,upgrade}`)

The command `civix generate:upgrader` should be revised to:

* Generate new/future upgraders based on this convention
* Update existing upgraders based on this convention

Ideally, if someone wants to stick with the old upgrader for a while (e.g. because they need to run on <v5.38), then that should be possible. This probably affects item `#5` above -- we should continue providing stubs in `myext.civix.php` during a transitional period.

**Comment by mattwire** [comment]
@totten I wonder if there is any way of auto-checking any of this, similar to the core code style checker?

There are some "checks" that I automatically do every time I touch an extension such as check for postInstall stub (if missing upgrader runs on install), regenerate civix etc. and the list above adds a whole load more things to check.

**Comment by totten** [comment]
@mattwire Yeah, some linting would be cool.

I guess in an ideal world we would update https://github.com/civicrm/coder with some hints (e.g. "if `CRM_(.*)_Upgrader` extends eponymous `CRM_(.*)_Upgrader_Base`, then show a warning about the preferred subclass)? I suppose there's a learning-curve to writing the sniffs for phpcs...

**Comment by colemanw** [comment]
@totten we're now 10 releases on from the core version that made this possible. Time to execute on this IMO. One way to ensure backward-compat is to read the `<compatibility>` tag in the `info.xml` and have civix auto-remove the boilerplate when it's over `5.38`.

**Comment by colemanw** [comment]
I just ran `civix upgrade` on an extension ('de.systopia.eck') and was surprised by the following message:

```
This extension does not implement hook_civicrm_postInstall, but this is included in newer templates. This is a typical example:

     1: /**
     2:  * Implements hook_civicrm_postInstall().
     3:  *
     4:  * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_postInstall
     5:  */
     6: function eck_civicrm_postInstall() {
     7:   _eck_civix_civicrm_postInstall();
     8: }

 ! [NOTE] If you use civix to facilitate database upgrades ("civix generate:upgrader"), then you should enable this     
 !        stub. Otherwise, it is not needed.                                                                            

 ! [NOTE] If you are unsure what to do, you can safely add comment-code. Comment-code will not change the behavior. It  
 !        merely provides an example to reference if you encounter issues in the future.                                

 Add eck_civicrm_postInstall? [Yes. Add live-code.]:
  [y] Yes. Add live-code.
  [c] Yes. Add comment-code.
  [n] No. Do not add anything.
```

Given that this extension's `info.xml` already contains `<upgrader>CRM_Eck_Upgrader</upgrader>` I think that message was actually incorrect. The hook *is* implemented, via the `<upgrader>` tag. Is that correct @totten ?

**Comment by mattwire** [comment]
@colemanw I'm not sure. Typically if postInstall is not defined you find that extension upgrades always run (even on install) because the schema version doesn't get set in the database. It's *possible* that changed with the changes introduced with `civix upgrade` but I don't think so.

**Comment by colemanw** [comment]
I've opened a PR to do this upgrade #270

**Comment by colemanw** [comment]
Thanks for merging @totten. This issue can be closed (I don't have perms to do so on this repo).
