### ISSUE TITLE
civix the hook_civicrm_menuXml is gone

### ISSUE THREAD

**Issue by jaapjansma** [totten/civix#244]
When generating a new extension and you add a page, a form or a settings page the url is not found in CiviCRM.

This caused by the fact that `hook_civicrm_menuXml` is missing form the boiler plate generated by civix. 

A work around is to add the following code to your `myextension.php` file:

```php

/**
 * Implements hook_civicrm_xmlMenu().
 *
 * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_xmlMenu
 */
function myextension_civicrm_xmlMenu(&$files) {
  foreach (glob(__DIR__ . '/xml/Menu/*.xml') as $file) {
    $files[] = $file;
  }
}

```

**Comment by colemanw** [comment]
@jaapjansma you just have to add the mixin tag to your info.xml, per https://github.com/totten/civix/pull/233

**Comment by totten** [comment]
@jaapjansma Yeah, to rewind a half-step -- civix v22.05 has converted several *boilerplate hooks* to *mixins*. This article describes the change in more detail: https://civicrm.org/blog/totten/civix-v2205-how-remove-million-lines-extra-code

Key points:

* If an extension was initialized before v22.05, then you should run `civix upgrade` to convert it. (*This removes the hooks and updates `info.xml`*).
* If you create a new extension on v22.05, it will activate mixins as-needed (*ex: `generate:page` needs to register menu items; so it activates `<mixin>menu-xml@1.0.0</mixin>`*). Here's how that should look: https://gist.github.com/totten/c15833c5fd5937924427b977cc2f3ff1

If that doesn't help solve the issue, then there could be some bug or omission. A quick-and-dirty resolution could be this: activate *all* mixins. (This is functionally equivalent to the old templates -- which activated all boilerplate.) This command should work on civix v22.05.5+:

```
civix mixin --enable-all
```

Of course, if there is some bug or omission, then it would be great to learn more (eg a link to an extension that doesn't upgrade cleanly; or a console log where it fails to enable a mixin). I do have a feeling that we'll find some cases that need more polish.

**Comment by jaapjansma** [comment]
Ah ok. I did not try the mix-in method I was not aware I should do that.

**Comment by colemanw** [comment]
Civix will automatically convert your extension to using mixins (in a backward-compatible way using shims) if you type `civix upgrade`.

**Comment by totten** [comment]
It sounds like we can close this. Feel free to reopen if there's another issue.
