### ISSUE TITLE
install doesn't run in test

### ISSUE THREAD

**Issue by eileenmcnaughton** [totten/civix#28]
I've created an install routine using Civix which works fine in my actual install but when I run the unit tests it doesn't - so, I have to manually create the table in my test db - which I don't think is how it is supposed to work ?

My extension is at
https://github.com/eileenmcnaughton/nz.co.fuzion.entitysetting

**Comment by totten** [comment]
https://github.com/civicrm/org.civicrm.testapalooza provides a better pattern for testing in an extension. 

A few key elements:
  * Explicitly control installation with [`Civi\Test::headless()`](https://github.com/civicrm/org.civicrm.testapalooza/blob/master/civi-test.md).
  * Don't use `CiviUnitTestCase`. Instead, use `PHPUnit_Framework_TestCase` and mix in properties (like `HeadlessInterface` and `TransactionalInterface`). `CiviUnitTestCase` sometimes does really aggressive things to the DB which can be at loggerheads with your installation logic. (Ex: Your installer registers some new option-values, but CiviUnitTestCase resets all the option-values.)
  * Example code: https://github.com/civicrm/org.civicrm.testapalooza/tree/phpunit
