### ISSUE TITLE
`Civibuild create` fails with Redis due to cached extensions

### ISSUE THREAD

**Issue by eileenmcnaughton** [totten/civix#287]
We've discussed this before @totten  but I don't think it has an issue.

When I run `civibuild create wmff` to recreate the `wmff` site (ie it has been used already & the cache is warm) it loads the list of hook-able extensions from `Redis` and it is the list that was enabled prior to the create. This means it is calling hooks (`alterMenu`) on extensions that are not enabled & fatals cos they call things that are not in the include path

Probably a judicious `flushAll` is enough - I'm not sure where though

**Comment by totten** [comment]
@eileenmcnaughton I'm not sure this is a `civix` thing... Perhaps this should be filed in `civicrm-buildkit` or `lab.c.o`?

**Comment by eileenmcnaughton** [comment]
this is the lab issue & yeah probably I intended civibuild not civix https://lab.civicrm.org/dev/core/-/issues/4159

**Comment by eileenmcnaughton** [comment]
MOved to https://github.com/civicrm/civicrm-buildkit/issues/765
