### ISSUE TITLE
camlCase and snake_case are not allowed in extension names?

### ISSUE THREAD

**Issue by adamwight** [totten/civix#37]
src/CRM/CivixBundle/Command/InitCommand.php only allows lowercase letters and numbers in the module name.  That seems overly restrictive.

**Comment by totten** [comment]
The extension short-name gets propagated/reused in multiple contexts (e.g. for hook-functions, class-namespaces, and l10n domains). I suspect that multi-word names would need some testing/transformation to work in all contexts. It would probably take someone a couple hours to sort through.

**Comment by michaelmcandrew** [comment]
see https://github.com/totten/civix/pull/122 for a PR which implements a solution to this. It doesn't allow camlCase or snake_case, but it does allow kebab-case which gets converted to camlCase snake_case as appropriate throughout the extension.

**Comment by UjenkOfficial** [comment]
src/CRM/CivixBundle/Command/InitCommand.php only allows lowercase letters and numbers in the module name. That seems overly restrictive.

**Comment by michaelmcandrew** [comment]
Keeping things simple means makes it easier to transform between the various cases that are needed in different places, e.g. my-extension in the extension name becomes MyExtension in classes and my_extension hook functions, etc.

If we permit other formats for extension names it becomes much harder to do these transformations automatically.

FYI, this is a best practice recommendation that civix enforces. My advice would be to stick with the convention You are welcome to manually try out other naming regimes. but might encounter unexpected results, esp. with 'automatically generated stuff'.

Interested to know what your use case is / what extension name you are trying to create.

**Comment by michaelmcandrew** [comment]
@totten - suggest that we close this one now

**Comment by totten** [comment]
Thank you, @michaelmcandrew et al. Agree this was addressed by #122 / v18.02.0.
