### ISSUE TITLE
getting an error when I was coping report

### ISSUE THREAD

**Issue by flik** [totten/civix#63]
sudo civix generate:report \  --copy CRM_Report_Form_Activity \ MyActivity Contact

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments.

**Comment by totten** [comment]
1. There's no need to use `sudo` unless you're doing lots of other things as root... which... would not be recommended.

2. When using the bash command-line, backslash is an escape character. With *backslash+newline*, it means "carry over to the next line". With *backslash+space*, it means "insert a literal space". Compare:

```bash
## Good example
civix generate:report --copy CRM_Report_Form_Activity MyActivity Contact

## Good example. Same thing, but with multiple lines
civix generate:report \
  --copy CRM_Report_Form_Activity \
  MyActivity Contact

## Bad example. This is putting literal spaces in the wrong places,
## which confuses the command parser.
civix generate:report \ --copy CRM_Report_Form_Activity \ MyActivity Contact
```

**Comment by flik** [comment]
thanks
