### ISSUE TITLE
Why this error is coming?

### ISSUE THREAD

**Issue by flik** [totten/civix#66]
Why this error is coming?

civix generate:page Compain  civicrm/compain

PHP Warning:  DOMDocument::load(): I/O warning : failed to load external entity "/var/www/html/crm/drupal7/sites/default/files/civicrm/ext/info.xml" in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/XML.php on line 53

Warning: DOMDocument::load(): I/O warning : failed to load external entity "/var/www/html/crm/drupal7/sites/default/files/civicrm/ext/info.xml" in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/XML.php on line 53
PHP Warning:  simplexml_import_dom(): Invalid Nodetype to import in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/XML.php on line 55

Warning: simplexml_import_dom(): Invalid Nodetype to import in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/XML.php on line 55
PHP Fatal error:  Call to a member function attributes() on a non-object in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/Info.php on line 63

Fatal error: Call to a member function attributes() on a non-object in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/Info.php on line 63

**Comment by flik** [comment]
Ok. I have fixed the issue.

**Comment by totten** [comment]
Glad it worked out.
