### ISSUE TITLE
another strange issue is coming now

### ISSUE THREAD

**Issue by flik** [totten/civix#71]
I was creating API and getting this error. Can you check and suggest something ?

sudo civix generate:api NewEntity NewAction
PHP Fatal error:  Call to a member function attributes() on a non-object in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/Info.php on line 63
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/civix:0
PHP   2. require() /usr/local/bin/civix:10
PHP   3. CRM\CivixBundle\Application::main() phar:///usr/local/bin/civix/bin/civix:22
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/civix/src/CRM/CivixBundle/Application.php:31
PHP   5. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/civix/vendor/symfony/console/Application.php:123
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/civix/vendor/symfony/console/Application.php:192
PHP   7. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/civix/vendor/symfony/console/Application.php:844
PHP   8. CRM\CivixBundle\Command\AddApiCommand->execute() phar:///usr/local/bin/civix/vendor/symfony/console/Command/Command.php:259
PHP   9. CRM\CivixBundle\Builder\Info->load() phar:///usr/local/bin/civix/src/CRM/CivixBundle/Command/AddApiCommand.php:47

Fatal error: Call to a member function attributes() on a non-object in phar:///usr/local/bin/civix/src/CRM/CivixBundle/Builder/Info.php on line 63

Call Stack:
    0.0002     116360   1. {main}() /usr/local/bin/civix:0
    0.0099     181228   2. require('phar:///usr/local/bin/civix/bin/civix') /usr/local/bin/civix:10
    0.0161     428936   3. CRM\CivixBundle\Application::main() phar:///usr/local/bin/civix/bin/civix:22
    0.0600    1657336   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/civix/src/CRM/CivixBundle/Application.php:31
    0.0668    1869540   5. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/civix/vendor/symfony/console/Application.php:123
    0.0671    1870032   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/civix/vendor/symfony/console/Application.php:192
    0.0672    1870320   7. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/civix/vendor/symfony/console/Application.php:844
    0.0682    1873116   8. CRM\CivixBundle\Command\AddApiCommand->execute() phar:///usr/local/bin/civix/vendor/symfony/console/Command/Command.php:259
    1.6192   16773016   9. CRM\CivixBundle\Builder\Info->load() phar:///usr/local/bin/civix/src/CRM/CivixBundle/Command/AddApiCommand.php:47

**Comment by flik** [comment]
ok. It is fixed and working now. 
What was the issue ?
I was executing this command out of the extension folder, Actual folder location was civicrm/ext/com.example.myextension
I was executing under civicrm/ext/

Then I was getting these errors. So, It will be helpful in feature for others. :)

**Comment by totten** [comment]
Agree that the error message isn't very clear - a better one would be great. 

Functionally, IMHO, it does make sense that you need to be in the folder of the intended extension when you run `generate:api`, `generate:page`, or similar. 

FWIW, all the examples in the [tutorial](https://wiki.civicrm.org/confluence/display/CRMDOC/Create+a+Module+Extension#CreateaModuleExtension-AddanAPIfunction) should be pretty explicit in showing the `cd` and CWD.
