### ISSUE TITLE
civix generate:api error

### ISSUE THREAD

**Issue by solve-it** [totten/civix#73]
i have civix set up i generated my extension,page,form and all but when i try to generate api i get the below error. mean while when i run cv help it shows also i have my environment variable set

`$ civix generate:api  Pcp get
'cv' is not recognized as an internal or external command,
operable program or batch file.

  [RuntimeException]
  Command failed (cv php:boot --level=full):

generate:api [--schedule [SCHEDULE]] [--] <<EntityName>> <<ActionName>>`

**Comment by totten** [comment]
As of v16.02.1, the `cv php:boot` stuff is embedded in `civix`, which should prevent this.
