### ISSUE TITLE
Support for multilingual upgrade in civicrm extension

### ISSUE THREAD

**Issue by sunilpawar** [totten/civix#77]
e.g.
we have some group and option value in extension, current extension upgrader not supporting for multilingual setup.

This is what we needed in sq/upgrade_xxx.sql.tpl file
SELECT id INTO @opt FROM `civicrm_option_group` WHERE `name` = 'uccife_industrie';
INSERT INTO `civicrm_option_value` (`option_group_id`, `name`, {localize field='label'}`label`{/localize}, `value`, `is_default`, `weight`) VALUES
  (@opt, 'art/design', {localize}'Art / Design'{/localize}, '419', 0, 45);

**Comment by totten** [comment]
Thanks, @sunilpawar !

I think this is a good idea to cover, although there are some changes we should make:
 * The signature for `executeSqlFile()` feels a bit magical -- e.g. you'd call it with `$this->executeSqlFile('myfile.sql')`, but then it would actually load a file named `myfile.sql.tpl`, but that behavior isn't clear from the function name. I think it's clearer to have a different helper function (e.g. `$this->executeSqlTemplate('myfile.sql.tpl')`).
 * I'm a little nervous about `new CRM_Upgrade_Form()` relying on hidden side-effects but do see how it resolves a conundrum.
 * `UpgraderBase` supports a naming convention to autoinstall and autoinstall (eg `*_install.sql`, `*_install.xml`, `*_uninstall.sql`). This should probably be extended to `*_install.mysql.tpl`.

In reviewing/merging the PR, I've made additional changes: 2648e04a1b, 9f2a8c17, 3ab5c2917
